name: Lint

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: phplint
        uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log