name: Lint

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: phplint
        uses: overtrue/phplint@5.5.0
        with:
          path: .
          options: --exclude=*.log
